### PR TITLE
Naming Shapes

### PR DESCRIPTION
**Pull request by OverCry**
When a multi-sided shape was originally made, they would all have the same default name.
Although this does not cause any issues functionality-wise, it is hard to read and use.

Now, an alert-esque response is provided for the user to provide a name.

### CODE REVIEW

**Review by AnubhavKhanna07 — CHANGES_REQUESTED** [review]
I think we should have an actual alert box pop up when the user is required to enter a variable name

**Comment by OverCry** [comment]
> I think we should have an actual alert box pop up when the user is required to enter a variable name

Modified

**Comment by AnubhavKhanna07** [comment]
Looks good now

**Review by AnubhavKhanna07 — APPROVED** [review]
Looks perfect now!

**Pull request merged**
